#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install
ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate
# https://github.com/karakeep-app/karakeep/issues/967
npm install -g corepack@0.31.0

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

release=$(curl -s https://api.github.com/repos/karakeep-app/karakeep/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')

secret==$(ynh_string_random --length=36)
ynh_app_setting_set --key=secret --value=$secret

# Set `service` settings to support `yunohost app shell` command
ynh_app_setting_set --key=service --value="$app-web.service"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

ynh_setup_source --dest_dir="/usr/bin/" --source_id="dlp"
chmod +x "/usr/bin/yt-dlp"

ynh_setup_source --dest_dir="/usr/bin/" --source_id="monolith"
chmod +x "/usr/bin/monolith"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# LOGROTATE
#=================================================
ynh_script_progression "Configuring logrotate to manage application logfiles"

ynh_config_add_logrotate

touch /var/log/$app/${app}-workers.log
touch /var/log/$app/${app}-web.log
touch /var/log/$app/${app}-$app.log

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}-browser" --template="karakeep-browser.service"
ynh_config_add_systemd --service="${app}-web" --template="karakeep-web.service"
ynh_config_add_systemd --service="${app}-workers" --template="karakeep-workers.service"

yunohost service add "${app}-workers" --description="Bookmark-everything app" --log="/var/log/$app/${app}-workers.log"
yunohost service add "${app}-web" --description="Bookmark-everything app" --log="/var/log/$app/${app}-web.log"
yunohost service add "${app}-browser" --description="Bookmark-everything app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL KARAKEEP
#=================================================
ynh_script_progression "Installing the app..."

export NEXT_TELEMETRY_DISABLED=1
export PUPPETEER_SKIP_DOWNLOAD="true"
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
export CI="true"
export DATA_DIR=$install_dir/db
export NEXTAUTH_SECRET=$secret

mkdir "$install_dir/db"

pushd "$install_dir"
  	ynh_hide_warnings pnpm install --frozen-lockfile
	ynh_hide_warnings pnpm run db:migrate
popd

pushd "$install_dir/apps/web"
	ynh_script_progression "Building the web..."
  	ynh_hide_warnings pnpm exec next build --experimental-build-mode compile
popd

pushd "$install_dir/apps/workers"
	ynh_script_progression "Building the workers..."
	ynh_hide_warnings pnpm build
	ynh_hide_warnings pnpm deploy --node-linker=isolated --filter @karakeep/workers --prod "$install_dir/apps/workers/prod/"
popd

pushd "$install_dir/apps/cli"
	ynh_script_progression "Building the cli..."
  	ynh_hide_warnings pnpm build
popd

pushd "$install_dir/apps/mcp"
	ynh_script_progression "Building the mcp..."
	ynh_hide_warnings pnpm build
popd

echo "$release" >$install_dir/version.txt

pushd "$install_dir/apps/workers/prod"
	ynh_hide_warnings pnpm add better-sqlite3 dotenv
popd

#remove unneeded files
ynh_safe_rm "$install_dir/apps/mobile"
ynh_safe_rm "$install_dir/apps/landing"

chmod -R 775 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="${app}-workers" --action="start"
ynh_systemctl --service="${app}-web" --action="start"
ynh_systemctl --service="${app}-browser" --action="start"

#pushd "$install_dir/db_migrations"
#	ynh_hide_warnings exec node index.js
#popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
