#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

release=$(curl -s https://api.github.com/repos/karakeep-app/karakeep/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install
ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-web" --action="stop"
ynh_systemctl --service="$app-workers" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="karakeep.env"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/karakeep.env"

chmod 600 "$install_dir/karakeep.env"
chown "$app:$app" "$install_dir/karakeep.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}-browser" --template="karakeep-browser.service"
ynh_config_add_systemd --service="${app}-web" --template="karakeep-web.service"
ynh_config_add_systemd --service="${app}-workers" --template="karakeep-workers.service"
#ynh_config_add_systemd --service="meilisearch" --template="meilisearch.service"

yunohost service add "${app}-workers" --description="Bookmark-everything app" --log="/var/log/$app/${app}-workers.log"
yunohost service add "${app}-web" --description="Bookmark-everything app" --log="/var/log/$app/${app}-web.log"
yunohost service add "${app}-browser" --description="Bookmark-everything app" --log="/var/log/$app/$app.log"
#yunohost service add "meilisearch" --description="Bookmark-everything app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL KARAKEEP
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir/apps/web"
	export NEXT_TELEMETRY_DISABLED=1
	export PUPPETEER_SKIP_DOWNLOAD="true"
	export CI="true"
  	ynh_hide_warnings pnpm install --frozen-lockfile
  	ynh_hide_warnings pnpm build
popd

pushd "$install_dir/apps/workers"
  	ynh_hide_warnings pnpm install --frozen-lockfile
popd

pushd "$install_dir/apps/cli"
  	ynh_hide_warnings pnpm install --frozen-lockfile
  	ynh_hide_warnings pnpm build
popd

pushd "$install_dir/packages/db"
  	ynh_hide_warnings pnpm migrate
popd

echo "$release" >$install_dir/version.txt

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-web" --action="start"
ynh_systemctl --service="$app-workers" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
